# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jeremie Martinez
tagline:          'Jeremie Blog'
description:      'I am an Android Software Developer. This is my personal blog.'
url:              'http://jeremie-martinez.com'
baseurl:          /

author:
  name:           'Jeremie Martinez'
  url:            'https://twitter.com/JeremMartinez'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           'https://github.com/jeremiemartinez/jeremiemartinez.github.com'
